# Site settings
name: DaveDavePicks
title: DaveDavePicks
description: 3D PRINTED, RESIN CAST AND HANDMADE PLECTRUMS AND THUMB PICKS
theme: jekyll-theme-midnight

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:title/
