# Site settings
title: DaveDavePicks
description: DaveDavePicks Plectrums and Thumb Picks
theme: jekyll-theme-slate

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:title/
