# Site settings
name: DaveDavePicks
title: null
description: null
theme: jekyll-theme-midnight

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:title/
