# Site settings
title: DaveDavePicks
description: DaveDavePicks plectrums and thumb picks
theme: jekyll-theme-midnight

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:title/
